DROP DATABASE IF EXISTS GuessTheNumberDBTest;
CREATE DATABASE GuessTheNumberDBTest;

USE GuessTheNumberDBTest;

CREATE TABLE Game (
	GameID INT PRIMARY KEY AUTO_INCREMENT,
    Answer CHAR(4) NOT NULL,
    IsFinished BIT NOT NULL
);

CREATE TABLE Round (
	RoundID INT PRIMARY KEY AUTO_INCREMENT,
    GameID INT NOT NULL,
    Guess CHAR(4) NOT NULL,
    GuessTime TIMESTAMP NOT NULL,
    Result CHAR(7) NOT NULL,
    FOREIGN KEY (GameID) REFERENCES Game(GameID)
);